# For more details on configuring Wrangler, see:
# https://developers.cloudflare.com/workers/wrangler/configuration/
name = "poma"
main = "src/server.ts"
compatibility_date = "2025-08-03"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[assets]
directory = "public"

[ai]
binding = "AI"
remote = true

[[durable_objects.bindings]]
name = "Chat"
class_name = "Chat"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Chat"]
