# For more details on configuring Wrangler, see:
# https://developers.cloudflare.com/workers/wrangler/configuration/
name = "poma"
main = "src/server/index.ts"
compatibility_date = "2025-08-03"
compatibility_flags = ["nodejs_compat"]

[vars]
MODEL_NAME="@cf/openai/gpt-oss-20b"

[observability]
enabled = true

[assets]
directory = "public"

[ai]
binding = "AI"
remote = true

[[durable_objects.bindings]]
name = "PomaAgent"
class_name = "PomaAgent"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["PomaAgent"]

